---
db:
  type: mysql
  host: localhost
  name: opar
  user: root
  pass: 
paths:
  base: /Users/tk/Desktop/Renee/OPAR/opar-web/
  templates: templates/
  conf: /Users/tk/Desktop/Renee/OPAR/opar-web/conf/
  static: static/
  mails: mails/
  uploads: /Users/tk/Desktop/Renee/OPAR/opar-web/uploads/
defaults:
  static: imprint
templates:
  base: opar.tmpl
  author: author.tmpl
  admin: admin.tmpl
logging: logging.web.conf
formid:
  expire: 300
  passwd_expire: 86400
time:
  deletion: 259200
recaptcha:
  public_key: public
  private_key: private
mail:
  smtp:
    host: your_smtp.example
    user: smtp_user
    pass: smtp_password
  from: opar@fqdn.example
  to: you@fqdn.example
  subjects:
    general: Mail from OPAR
    forgot_password: Forgot password
    registration: Account for OPAR requested
    comment_created: A new comment for one of your packages
  tag: [OPAR]
password:
  salt: OPAR
admin:
  startpage: menu
errors:
  captcha:
    headline: Captcha not Correct!
    message: Your captcha solution was wrong.
  formid:
    headline: Invalid FormID!
    message: The form id expired, please try again.
  input:
    headline: Invalid Input!
    message: One or more fields were not filled or not filled correctly.
  package_not_found:
    headline: Package not Found!
    message: The package you have requested cannot be found.
  username_exists:
    headline: User already exists!
    message: The username you have chosen is already in use.
  login_incorrect:
    headline: Login incorrect!
    message: Please check your username and your password.
  author_not_found:
    headline: Author not found!
    message: The author you have request cannot be found
  404:
    headline: File not found!
    message: The file you have request cannot be found
  500:
    headline: An error occured!
    message: Please drop us a line (opar@perl-services.de) and send us more details about the situation where the error occured.
utils:
  config: /home/opar/opar_sources/conf
  perltidy:
    config: perltidyrc
  perlcritic:
    config: perlcriticrc
general:
  perl_version: 5.008001
rss:
  publisher: perl-services.de
  creator: perl-services.de
  rights: Perl-Services.de
help:
  registration:
    username: Username has to be longer than 3 characters (A-Z, a-z), no special characters
    email: Must be in valid email format
otrs:
  index: /home/opar/otrs.xml
app:
  reverse_proxy: 1
  secret: 2387t813797198fasdhvljashdsadasld13589(51)
twitter:
  url: http://opar/dist/
  consumer_key: 13djvks230iv
  consumer_secret: ljaasdlasjrlvbvkkrlraillshyl23131
  token: 32oi1f10o1ohcoh
  token_secret: avdfkoqjwlvjlsdjf
notifications:
  comment_created:
    label: Notify me when a comment for one of my packages is created
    types:
      - Mail

