---
db:
  type: mysql
  host: localhost
  name: opar
  user: root
  pass: 
paths:
  base: /Users/tk/Desktop/Renee/OPAR/opar-web/
  templates: templates/
  conf: /Users/tk/Desktop/Renee/OPAR/opar-web/conf/
  static: static/
  mails: mails/
  uploads: /Users/tk/Desktop/Renee/OPAR/opar-web/uploads/
defaults:
  static: imprint
templates:
  base: opar.tmpl
  author: author.tmpl
  admin: admin.tmpl
logging: logging.web.conf
formid:
  expire: 300
  passwd_expire: 86400
time:
  deletion: 259200
  deletion_admin: 86400
recaptcha:
  public_key: 6LcMqsESAAAAAD0ioZiFwRNDe3OcftdzwL_XIV81
  private_key: 6LcMqsESAAAAADEX18C3wWHJT7vGXWyE7OCWWnTm
mail:
  smtp:
    host: mail.perl-services.de
    user: opar@perl-services.de
    pass: 391TWgb!
  from: opar@perl-services.de
  to: reb@perl-services.de
  subjects:
    general: Mail from OPAR
    forgot_password: Forgot password
    registration: Account for OPAR requested
    feedback: Feedback
  tag: [OPAR]
password:
  salt: OPAR
admin:
  startpage: menu
errors:
  captcha:
    headline: Captcha not Correct!
    message: Your captcha solution was wrong.
  formid:
    headline: Invalid FormID!
    message: The form id expired, please try again.
  input:
    headline: Invalid Input!
    message: One or more fields were not filled or not filled correctly.
  package_not_found:
    headline: Package not Found!
    message: The package you have requested cannot be found.
  username_exists:
    headline: User already exists!
    message: The username you have chosen is already in use.
utils:
  config: /Users/tk/Desktop/Renee/OPAR/opar-web/conf
  perltidy:
    config: perltidyrc
  perlcritic:
    config: perlcriticrc
general:
  perl_version: 5.008001
rss:
  publisher: perl-services.de
  creator: perl-services.de
  rights: Perl-Services.de
help:
  registration:
    username: Username has to be longer than 3 characters (A-Z, a-z), no special characters
    email: Must be in valid email format
