---
schema:
  opr_user:
    user_id: INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
    user_name: VARCHAR(255) 
    user_password: VARCHAR(255) 
    mail: VARCHAR(255) 
    website: VARCHAR(255) 
    session_id: VARCHAR(255)
    active: TINYINT
    registered: INTEGER
    realname: VARCHAR(255)
  opr_package_names:
    name_id: INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT
    package_name: VARCHAR(255)
  opr_package:
    package_id: INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
    uploaded_by: INTEGER NOT NULL
    name_id: INTEGER NOT NULL
    description: VARCHAR(255)
    version: VARCHAR(255)
    framework: VARCHAR(255)
    path: VARCHAR(255)
    is_in_index: INTEGER
    website: VARCHAR(255)
    bugtracker: VARCHAR(255)
    upload_time: VARCHAR(255)
    virtual_path: VARCHAR(255)
    deletion_flag: VARCHAR(255)
    documentation: VARCHAR(255)
  opr_package_dependency:
    dependency_id: INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
    package_id: INTEGER NOT NULL
    dependency_type: VARCHAR(255)
    dependency_version: VARCHAR(255)
  opr_formid:
    formid: VARCHAR(255) NOT NULL PRIMARY KEY
    used: INTEGER
    expire: INTEGER
  opr_package_author:
    user_id: INTEGER NOT NULL
    name_id: INTEGER NOT NULL
    is_main_author: INTEGER
    primary_key: user_id, name_id
  opr_job_queue:
    job_id: INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
    type_id: INTEGER NOT NULL
    package_id: INTEGER NOT NULL
    created: INTEGER NOT NULL
    changed: INTEGER NOT NULL
    job_state: VARCHAR(255)
  opr_job_type:
    type_id: INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
    type_label: VARCHAR(255)
